Repository jabardigitalservice/portal-jabar-services, pull requests merged in 2021-09, with the labels that each got.

#31 add migrater
  core-service/Makefile
  core-service/docker/Dockerfile
  core-service/src/cmd/main.go
  core-service/src/cmd/migrater/main.go
  core-service/src/config/config.go
  core-service/src/config/db.go
  core-service/src/database/connection.go
  core-service/src/database/migrations/20210906032833_add_column_priority_on_event_table.down.sql
  core-service/src/go.mod
  core-service/src/go.sum
Labels: enhancement

#33 Feature feedback
  core-service/src/database/migrations/20210914162305_create_feedback_table.down.sql
  core-service/src/database/migrations/20210914162305_create_feedback_table.up.sql
  core-service/src/delivery/http/feedback_handler.go
  core-service/src/delivery/http/handlers.go
  core-service/src/domain/feedback.go
  core-service/src/go.mod
  core-service/src/go.sum
  core-service/src/repositories/mysql/mysql.go
  core-service/src/repositories/mysql/mysql_feedback.go
  core-service/src/usecases/feedback_ucase.go
  core-service/src/usecases/usecases.go
Labels: enhancement

#35 Feature agenda
  core-service/src/config/db.go
  core-service/src/database/migrations/20210906032833_add_column_priority_on_event_table.down.sql
  core-service/src/database/migrations/20210906032833_add_column_priority_on_event_table.up.sql
  core-service/src/database/migrations/20210916020704_add_column_priorities_on_events_table.down.sql
  core-service/src/database/migrations/20210916020704_add_column_priorities_on_events_table.up.sql
  core-service/src/repositories/mysql/mysql_event.go
Labels: enhancement

#38 adjustment query select data per week
  core-service/src/database/migrations/20210830234412_create_events_table.up.sql
  core-service/src/domain/event.go
  core-service/src/repositories/mysql/mysql_event.go
Labels: bug

#41 Feature agenda
  core-service/src/database/migrations/20210830234412_create_events_table.up.sql
  core-service/src/database/migrations/20210916020704_add_column_priorities_on_events_table.down.sql
  core-service/src/database/migrations/20210916020704_add_column_priorities_on_events_table.up.sql
  core-service/src/database/migrations/20210920070419_add_column_priority_on_events.down.sql
  core-service/src/database/migrations/20210920070419_add_column_priority_on_events.up.sql
  core-service/src/delivery/http/helper.go
  core-service/src/domain/event.go
  core-service/src/repositories/mysql/mysql_event.go
Labels: bug

#42 Add field type on events
  core-service/src/database/migrations/20210830234412_create_events_table.up.sql
  core-service/src/database/migrations/20210922034537_add_column_type_on_event_table.down.sql
  core-service/src/database/migrations/20210922034537_add_column_type_on_event_table.up.sql
  core-service/src/delivery/http/event_handler.go
  core-service/src/domain/event.go
  core-service/src/repositories/mysql/mysql_event.go
Labels: enhancement

#43 refactor migrations pre-dev
  core-service/src/database/migrations/1629281242_initialize_schema.down.sql
  core-service/src/database/migrations/1629281242_initialize_schema.up.sql
  core-service/src/database/migrations/20210830233956_create_areas_table.down.sql
  core-service/src/database/migrations/20210830233956_create_areas_table.up.sql
  core-service/src/database/migrations/20210830234412_create_events_table.down.sql
  core-service/src/database/migrations/20210830234412_create_events_table.up.sql
  core-service/src/database/migrations/20210913103442_add_column_views_on_news_table.down.sql
  core-service/src/database/migrations/20210913103442_add_column_views_on_news_table.up.sql
  core-service/src/database/migrations/20210914162305_create_feedback_table.down.sql
  core-service/src/database/migrations/20210914162305_create_feedback_table.up.sql
  core-service/src/database/migrations/20210920070419_add_column_priority_on_events.down.sql
  core-service/src/database/migrations/20210920070419_add_column_priority_on_events.up.sql
  core-service/src/database/migrations/20210920152239_add_column_highlight_on_news_table.down.sql
  core-service/src/database/migrations/20210920152239_add_column_highlight_on_news_table.up.sql
  core-service/src/database/migrations/20210922034537_add_column_type_on_event_table.down.sql
  core-service/src/database/migrations/20210922034537_add_column_type_on_event_table.up.sql
Labels: good first issue

#44 FE no longer send sort order & sort by, used this by default
  core-service/src/repositories/mysql/mysql_event.go
Labels: enhancement
