Repository jabardigitalservice/portal-jabar-services, pull requests merged in 2023-04, with the labels that each got.

#421 infra: set-new-registry & improvement ci/cd
  .github/workflows/app-build-push.yml
  .github/workflows/app-release.yml
  .github/workflows/app-worker-build-push.yml
  .github/workflows/app-worker-release.yml
  .github/workflows/ci.yml
  core-service/docker/Dockerfile
  service-worker/docker/Dockerfile
Labels: devops

#422 infra: set-image-release ci/cd
  .github/workflows/app-release.yml
  .github/workflows/app-worker-release.yml
Labels: devops

#420 core-svc-feat(master-data-service): master data publication module
  core-service/src/cmd/server/handler.go
  core-service/src/cmd/server/repository.go
  core-service/src/cmd/server/usecase.go
  core-service/src/database/migrations/20230403043306_add_column_title_on_applications_table.down.sql
  core-service/src/database/migrations/20230403043306_add_column_title_on_applications_table.up.sql
  core-service/src/database/migrations/20230404041326_create_masterdata_publications_table.down.sql
  core-service/src/database/migrations/20230404041326_create_masterdata_publications_table.up.sql
  core-service/src/domain/main_service.go
  core-service/src/domain/master_data_publication.go
  core-service/src/domain/master_data_service.go
  core-service/src/modules/master-data-publication/delivery/http/publication_handler.go
  core-service/src/modules/master-data-publication/repository/mysql/mysql_publication.go
  core-service/src/modules/master-data-publication/usecase/publication_ucase.go
  core-service/src/modules/master-data-service/delivery/http/mds_handler.go
  core-service/src/modules/mds-application/repository/mysql/mysql_mds_application.go
  core-service/src/modules/mds-main-service/repository/mysql/mysql_main_service.go
Labels: new feature

#423 core-svc-feat(master-data-service): add archives list mds endpoint
  core-service/src/domain/master_data_service.go
  core-service/src/modules/master-data-service/delivery/http/mds_handler.go
  core-service/src/modules/master-data-service/usecase/mds_ucase.go
Labels: new feature

#425 hotfix-core-svc-feat(global-search): controlling index size for better search results experiences
  core-service/.env.example
  core-service/src/cmd/server/repository.go
  core-service/src/config/elastic.go
  core-service/src/modules/search/delivery/http/search_handler.go
  core-service/src/modules/search/repository/elastic/elastic_search.go
Labels: enhancement

#426 core-svc-feat(global-search): hotfix error slice bonds out
  core-service/src/modules/search/delivery/http/search_handler.go
Labels: hotfix

#427 core-svc-feat(publications): add list api endpoint of publication
  core-service/src/domain/master_data_publication.go
  core-service/src/modules/master-data-publication/delivery/http/publication_handler.go
  core-service/src/modules/master-data-publication/repository/mysql/mysql_publication.go
  core-service/src/modules/master-data-publication/repository/mysql/mysql_publication_helper.go
  core-service/src/modules/master-data-publication/usecase/publication_ucase.go
Labels: new feature

#428 core-svc-feat(publications): add api delete publication
  core-service/src/domain/master_data_publication.go
  core-service/src/modules/master-data-publication/delivery/http/publication_handler.go
  core-service/src/modules/master-data-publication/repository/mysql/mysql_publication.go
  core-service/src/modules/master-data-publication/repository/mysql/mysql_publication_test.go
  core-service/src/modules/master-data-publication/usecase/publication_ucase.go
Labels: new feature

#429 core-svc-feat(publications): add api endpoint detail publication
  core-service/src/domain/master_data_publication.go
  core-service/src/modules/master-data-publication/delivery/http/publication_handler.go
  core-service/src/modules/master-data-publication/repository/mysql/mysql_publication.go
  core-service/src/modules/master-data-publication/usecase/publication_ucase.go
Labels: new feature

#430 core-svc-feat(publications): add api endpoint tabs list aggregations
  core-service/src/domain/master_data_publication.go
  core-service/src/modules/master-data-publication/delivery/http/publication_handler.go
  core-service/src/modules/master-data-publication/repository/mysql/mysql_publication.go
  core-service/src/modules/master-data-publication/usecase/publication_ucase.go
Labels: new feature

#431 core-svc-feat(publications): add api endpoint update publication
  core-service/src/domain/master_data_publication.go
  core-service/src/modules/master-data-publication/delivery/http/publication_handler.go
  core-service/src/modules/master-data-publication/repository/mysql/mysql_publication.go
  core-service/src/modules/master-data-publication/usecase/publication_ucase.go
Labels: new feature

#432 core-svc-feat(publications): fix usecase to choose mds id
  core-service/src/modules/master-data-publication/usecase/publication_ucase.go
Labels: bug
